=== oco-research/connector-registry/connector.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "connector-schema",
    "description": "A schema for the Adobe Connector",
    "type": "object",
    "properties": {
        "name": {
          "type": "string",
          "description": "The unique connector name"
        },
        "author": {
          "type": "string",
          "description": "The name of the author"
        },
        "version": {
          "type": "string",
          "description": "The version of the connector"
        },
        "description": {
          "type": "string",
          "description": "A description of the connector"
        },
        "provider": {
          "type": "object",
          "description": "The connector source"
        }
    },
    "required":["name", "author", "version", "description", "provider"],
    "additionalProperties" : false
  }

=== oco-research/connector-registry/connectors/test-2.json
{
    "name": "Test connector 2",
    "version": "0.0.3333333",
    "description": "super 333",
    "author": "VZqqq",
    "provider": {
        "name": "Commerce",
        "handler": {
          "graphql": {
            "endpoint": "https://venia.magento.com/graphql/"
          }
        },
        "transforms": [
          {
            "rename": {
              "mode": "bare | wrap",
              "renames": [
                {
                  "from": {
                    "type": "Query",
                    "field": "compareList"
                  },
                  "to": {
                    "type": "Query",
                    "field": "productCompareList"
                  }
                }
              ]
            }
          },
          {
            "filterSchema": {
              "mode": "bare | wrap",
              "filters": [
                "Query.!category",
                "Query.!customerOrders",
                "Query.!urlResolver",
                "Query.!wishlist"
              ]
            }
          },
          {
            "cache": [
              {
                "field": "Query.storeConfig",
                "invalidate": {
                  "ttl": 3600
                }
              }
            ]
          }
        ]
      }
}

=== oco-research/connector-registry/connectors/test-connector.json
{
    "name": "Test connector",
    "version": "0.0.1",
    "description": "super description",
    "author": "VZW",
    "provider": {
        "name": "Commerce",
        "handler": {
          "graphql": {
            "endpoint": "https://venia.magento.com/graphql/"
          }
        },
        "transforms": [
          {
            "rename": {
              "mode": "bare | wrap",
              "renames": [
                {
                  "from": {
                    "type": "Query",
                    "field": "compareList"
                  },
                  "to": {
                    "type": "Query",
                    "field": "productCompareList"
                  }
                }
              ]
            }
          },
          {
            "filterSchema": {
              "mode": "bare | wrap",
              "filters": [
                "Query.!category",
                "Query.!customerOrders",
                "Query.!urlResolver",
                "Query.!wishlist"
              ]
            }
          },
          {
            "cache": [
              {
                "field": "Query.storeConfig",
                "invalidate": {
                  "ttl": 3600
                }
              }
            ]
          }
        ]
      }
}
